{
	"type":"Scene",
	"props":{
		"name":"Hero_01",
		"enableFog":false,
		"fogStart":0,
		"fogRange":300
	},
	"customProps":{
		"skyBox":{},
		"lightmaps":[],
		"ambientColor":[
			0.212,
			0.227,
			0.259
		],
		"fogColor":[
			0.5,
			0.5,
			0.5
		]
	},
	"child":[
		{
			"type":"Sprite3D",
			"props":{
				"isStatic":false,
				"name":"Hero_01"
			},
			"customProps":{
				"layer":9,
				"translate":[
					0,
					0,
					0
				],
				"rotation":[
					0,
					0,
					0,
					-1
				],
				"scale":[
					1,
					1,
					1
				]
			},
			"components":{
				"BoxCollider":{
					"isTrigger":false,
					"center":[
						0,
						1.025615,
						0
					],
					"size":[
						1,
						2.094039,
						1
					]
				},
				"Rigidbody":{}
			},
			"child":[
				{
					"type":"Sprite3D",
					"props":{
						"isStatic":false,
						"name":"Offset"
					},
					"customProps":{
						"layer":0,
						"translate":[
							0,
							0,
							0
						],
						"rotation":[
							0,
							0,
							0,
							-1
						],
						"scale":[
							1,
							1,
							1
						]
					},
					"components":{},
					"child":[
						{
							"type":"Sprite3D",
							"props":{
								"isStatic":false,
								"name":"hero01_action"
							},
							"customProps":{
								"layer":0,
								"translate":[
									0,
									0,
									0
								],
								"rotation":[
									0,
									0,
									0,
									-1
								],
								"scale":[
									1,
									1,
									1
								]
							},
							"components":{
								"Animator":{
									"avatar":{
										"path":"Assets/1001/Art/Models/Hero/hero01/hero01_action-hero01_action-hero01_actionAvatar.lav",
										"linkSprites":{
											"Bone006":[
												"Bone006"
											],
											"Bip001 Spine1":[
												"Bip001 Spine1"
											]
										}
									},
									"clipPaths":[
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_run.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_run_left.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_run_right.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_shovel.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_jump.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_jump_setdown.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_down.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_stagger_l.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_stagger_r.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_lost1_01.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_jump_hello.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_jump_roll1.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_jump_roll2.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_jump_left.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_jump_right.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_flay.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_flay_fall.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_down.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_jump.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_jump01.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_jump02.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_jump03.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_left.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_right.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_run.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_setdown.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_shovel.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_skidding.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_jump04.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_up_skb.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_jump05.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_huaxiang.lani"
									],
									"playOnWake":true
								}
							},
							"child":[
								{
									"type":"Sprite3D",
									"props":{
										"isStatic":false,
										"name":"Bone006"
									},
									"customProps":{
										"layer":0,
										"translate":[
											0.005090956,
											-0.02602637,
											0.1108699
										],
										"rotation":[
											0.009306526,
											9.652279E-05,
											0.01038965,
											-0.9999027
										],
										"scale":[
											1,
											0.9999999,
											1
										]
									},
									"components":{},
									"child":[
										{
											"type":"MeshSprite3D",
											"props":{
												"isStatic":false,
												"name":"huaban"
											},
											"customProps":{
												"layer":0,
												"translate":[
													0,
													-0.35,
													-0.1
												],
												"rotation":[
													0,
													0,
													0,
													-1
												],
												"scale":[
													0.1,
													0.1,
													0.1
												],
												"meshPath":"Assets/1001/Art/Models/Hero/huaban/huaban-huaban.lm",
												"materials":[
													{
														"type":"Laya.BlinnPhongMaterial",
														"path":"Assets/1001/Art/Models/Hero/huaban/Materials/huaban.lmat"
													}
												]
											},
											"components":{},
											"child":[]
										}
									]
								},
								{
									"type":"Sprite3D",
									"props":{
										"isStatic":false,
										"name":"Bip001 Spine1"
									},
									"customProps":{
										"layer":0,
										"translate":[
											6.130453E-07,
											1.431847,
											-0.0287795
										],
										"rotation":[
											-0.5118297,
											-0.4878828,
											-0.5118297,
											-0.4878843
										],
										"scale":[
											0.9999998,
											0.9999998,
											1
										]
									},
									"components":{},
									"child":[
										{
											"type":"MeshSprite3D",
											"props":{
												"isStatic":false,
												"name":"BonePoint"
											},
											"customProps":{
												"layer":0,
												"translate":[
													0.177,
													-0.407,
													0
												],
												"rotation":[
													0,
													0,
													0,
													-1
												],
												"scale":[
													0.65,
													0.65,
													0.65
												],
												"meshPath":"Assets/1001/Art/Models/LayaPlane/Plane-Plane.lm",
												"materials":[
													{
														"type":"Laya.BlinnPhongMaterial",
														"path":"Assets/1001/Art/Models/Hero/hero01/Materials/hero_dt01.lmat"
													}
												]
											},
											"components":{
												"BoxCollider":{
													"isTrigger":false,
													"center":[
														0,
														0,
														0
													],
													"size":[
														1,
														1,
														1
													]
												}
											},
											"child":[]
										}
									]
								},
								{
									"type":"SkinnedMeshSprite3D",
									"props":{
										"isStatic":false,
										"name":"hero_dt01"
									},
									"customProps":{
										"layer":0,
										"translate":[
											0,
											0,
											0
										],
										"rotation":[
											0.7071068,
											0,
											0,
											-0.7071067
										],
										"scale":[
											1,
											1,
											1
										],
										"rootBone":"Bip001 Pelvis",
										"boundBox":{
											"min":[
												-1.02709,
												-0.4415158,
												-0.8280308
											],
											"max":[
												1.626746,
												0.5697856,
												0.8280281
											]
										},
										"boundSphere":{
											"center":[
												0.299828,
												0.0641349,
												-1.311302E-06
											],
											"radius":1.643784
										},
										"materials":[
											{
												"type":"Laya.BlinnPhongMaterial",
												"path":"Assets/1001/Art/Models/Hero/hero01/Materials/hero_dt01.lmat"
											}
										],
										"meshPath":"Assets/1001/Art/Models/Hero/hero01/hero01_action-hero_dt01.lm"
									},
									"components":{},
									"child":[]
								}
							]
						}
					]
				}
			]
		}
	]
}